osx_image: xcode9.1
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1
before_install:
# Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
#  - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --project-directory=Example --repo-update
  - bundle exec pod install --project-directory=Firestore/Example --no-repo-update

script:
  - "! git grep -I ' $'" # Fail on trailing whitespace in non-binary files
  - ./test.sh

# TODO fix os_log deprecation warning in FIRLogger to remove --allow-warnings
  - bundle exec pod lib lint FirebaseCore.podspec --allow-warnings

# TODO - Uncomment subsequent lines once FirebaseCore source repo is in public Specs repo
#  - bundle exec pod lib lint FirebaseAuth.podspec
#  - bundle exec pod lib lint FirebaseDatabase.podspec
#  - bundle exec pod lib lint FirebaseMessaging.podspec --allow-warnings #pending #390 fix
#  - bundle exec pod lib lint FirebaseStorage.podspec
#  - bundle exec pod lib lint Firestore/Firestore.podspec

branches:
  only:
    - master
