language: objective-c
osx_image: xcode8.2

env:
 matrix:
  - SCRIPT="set -o pipefail && xcodebuild clean build -project Uploadcare/Uploadcare.xcodeproj -target Uploadcare | xcpretty -f `xcpretty-travis-formatter`"
  - SCRIPT="set -o pipefail && xcodebuild clean build -workspace Example/Example.xcworkspace -scheme Example CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`"

notifications:
  email: false

before_script:
- gem install xcpretty-travis-formatter

script:
 - eval $SCRIPT